import { CatalogueItem, VideoItem, SiteSettings } from '../types';

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  companyName: 'Vedant Bhomi Venture',
  brandName: 'Vedaanth ECO Buildcon (VEBCO)',
  tagline: 'Eco Friendly Construction',
  serviceAreas: [
    'Bangalore',
    'Karnataka',
    'Tamil Nadu',
    'Andhra Pradesh'
  ],
  whatsappMessage: 'Hello Vedant Bhomi Venture, I would like to consult on an eco-friendly construction project. My location is: ',
  phone: '+91 9742163589',
  phone_raw: '919742163589',
  whatsapp_number: '+919742163589',
  email_primary: 'vedaanthecobuildcon@gmail.com',
  email_secondary: 'vebcoadm@gmail.com',
  address: 'Bommasandra Jigani Link Rd, Jigani, Karnataka 560105, India',
  hours: 'Open 24 hours',
  youtube_url: 'https://www.youtube.com/@vedaanthecobuildcon7626',
  whatsapp_catalogue_url: 'https://wa.me/c/919742163589',
  hero_headline: 'Sustainable Living Built with Earth & Precision',
  hero_subtext: 'Vedant Bhomi Venture (also known as Vedaanth ECO Buildcon / VEBCO) crafts vernacular, climate-responsive homes and commercial buildings using CSEB mud bricks and mortar-free interlocking brick technology across Bangalore, Karnataka, Tamil Nadu, and Andhra Pradesh.',
  about_story: 'Vedant Bhomi Venture (also known as Vedaanth ECO Buildcon / VEBCO) is a premier construction company working on vernacular architecture and innovative sustainable technology using CSEB (Compressed Stabilized Earth Blocks) and Interlocking bricks across Bangalore, Karnataka, Tamil Nadu, and Andhra Pradesh. Interlocking bricks lock into each other, giving the wall exceptional structural strength without cement mortar bonding. About 60% of cement and sand is saved, water usage is drastically reduced, and work is completed in fast-track mode with our head office at Jigani, Karnataka.',
};

export const SEED_CATALOGUE_ITEMS: CatalogueItem[] = [
  {
    id: '11111111-1111-1111-1111-111111111001',
    title: 'CSEB Mud Bricks House',
    slug: 'cseb-mud-bricks-house',
    description: 'We build houses using Compressed Stabilized Earth Blocks (CSEB), offering thermal comfort, natural aesthetics, and exceptional structural longevity with minimal environmental footprint.',
    price: 2750,
    price_unit: 'per sq ft',
    category: 'Residential House',
    is_featured: true,
    visible: true,
    sort_order: 1,
    images: [],
  },
  {
    id: '11111111-1111-1111-1111-111111111002',
    title: 'New ECO Model House',
    slug: 'new-eco-model-house',
    description: 'New model house available featuring optimized spatial planning, exposed interlocking bricks, passive cooling design, and fast-track execution.',
    price: 2000,
    price_unit: 'per sq ft',
    category: 'Residential House',
    is_featured: true,
    visible: true,
    sort_order: 2,
    images: [],
  },
  {
    id: '11111111-1111-1111-1111-111111111003',
    title: 'ECO Friendly House Construction',
    slug: 'eco-friendly-house-construction',
    description: 'Turnkey eco-friendly house construction engineered for sustainability. Saves 60% cement and sand while delivering naturally cool indoor temperatures.',
    price: 2300,
    price_unit: 'per sq ft',
    category: 'Residential House',
    is_featured: true,
    visible: true,
    sort_order: 3,
    images: [],
  },
  {
    id: '11111111-1111-1111-1111-111111111004',
    title: 'Resort & Cottages',
    slug: 'resort-cottages',
    description: 'Exposed Brick and Interlocking mud brick cottage designs for eco resorts, farm retreats, and nature getaways blending harmoniously with surrounding landscapes.',
    price: 1700,
    price_unit: 'per sq ft',
    category: 'Resorts & Cottages',
    is_featured: true,
    visible: true,
    sort_order: 4,
    images: [],
  },
  {
    id: '11111111-1111-1111-1111-111111111005',
    title: 'Earth Bricks',
    slug: 'earth-bricks',
    description: 'Specialized earth brick construction leveraging soil stabilized blocks for sturdy, climate-resilient residential and farm buildings.',
    price: 2100,
    price_unit: 'per sq ft',
    category: 'Residential House',
    is_featured: false,
    visible: true,
    sort_order: 5,
    images: [],
  },
  {
    id: '11111111-1111-1111-1111-111111111006',
    title: 'Traditional House',
    slug: 'traditional-house',
    description: 'Authentic traditional courtyard houses built with natural clay and earth blocks, central courtyards (thotti mane / nadumuttam), and classical vernacular detailing.',
    price: 1950,
    price_unit: 'per sq ft',
    category: 'Traditional Courtyard',
    is_featured: false,
    visible: true,
    sort_order: 6,
    images: [],
  },
  {
    id: '11111111-1111-1111-1111-111111111007',
    title: 'Contemporary House Model',
    slug: 'contemporary-house-model',
    description: 'Modern contemporary aesthetic combined with eco-friendly interlocking bricks, large openings, cross ventilation, and sleek earth-tone finishes.',
    price: 1850,
    price_unit: 'per sq ft',
    category: 'Residential House',
    is_featured: false,
    visible: true,
    sort_order: 7,
    images: [],
  },
  {
    id: '11111111-1111-1111-1111-111111111008',
    title: 'Commercial Projects',
    slug: 'commercial-projects',
    description: 'Turnkey commercial buildings, creative studio spaces, eco-resort dining halls, and institutional architecture built with fast-track precision.',
    price: 2000,
    price_unit: 'per sq ft',
    category: 'Commercial Building',
    is_featured: false,
    visible: true,
    sort_order: 8,
    images: [],
  },
  {
    id: '11111111-1111-1111-1111-111111111009',
    title: 'Mud Bricks',
    slug: 'mud-bricks',
    description: 'High-density, precision-pressed Compressed Stabilized Earth Blocks (CSEB) and interlocking soil bricks supplied directly for green building initiatives.',
    price: null,
    price_unit: 'Contact for price',
    category: 'Raw Materials',
    is_featured: false,
    visible: true,
    sort_order: 9,
    images: [],
  },
];

export const SEED_VIDEOS: VideoItem[] = [
  {
    id: 'vid-1',
    title: 'Eco Friendly mud house using CSEB bricks. Traditional Courtyard House at Hosur',
    youtube_id: 'oZ5_G3cZ8tA',
    description: 'Traditional courtyard house construction featuring CSEB mud bricks at Hosur.',
    visible: true,
    sort_order: 1,
  },
  {
    id: 'vid-2',
    title: 'Eco Friendly House Construction. CSEB Mud Bricks House. Ongoing Traditional Courtyard',
    youtube_id: 'lM0a9C4Z0w0',
    description: 'Walkthrough of ongoing traditional courtyard construction using CSEB earth blocks.',
    visible: true,
    sort_order: 2,
  },
  {
    id: 'vid-3',
    title: 'Eco Friendly CSEB Mud House Using CSEB Bricks & Natural Stone',
    youtube_id: 's1L6jO5xTmA',
    description: 'Exposed earth bricks combined with natural stone masonry for enduring vernacular beauty.',
    visible: true,
    sort_order: 3,
  },
  {
    id: 'vid-4',
    title: 'Interlocking Bricks House construction',
    youtube_id: 'kU8V9W2mH4Q',
    description: 'Fast-track wall assembly demonstrating precision interlocking mortar-free technology.',
    visible: true,
    sort_order: 4,
  },
  {
    id: 'vid-5',
    title: '2BHK Flats for Sale Interlocking Mud Bricks used',
    youtube_id: 'qP4nL3wK9vE',
    description: 'Sustainable multi-unit residential flats built with high thermal efficiency interlocking bricks.',
    visible: true,
    sort_order: 5,
  },
  {
    id: 'vid-6',
    title: 'Ongoing project using Interlocking Bricks @ Bangalore',
    youtube_id: 'jK7mN2pL9wX',
    description: 'Site visit at Bangalore project showcasing clean exposed brickwork and structural columns.',
    visible: true,
    sort_order: 6,
  },
  {
    id: 'vid-7',
    title: 'Ongoing Farmhouse projects using Interlocking bricks & laterite stone',
    youtube_id: 'bV5nC8xL2qY',
    description: 'Serene farmhouse project integrating interlocking soil blocks with coastal laterite stone.',
    visible: true,
    sort_order: 7,
  },
  {
    id: 'vid-8',
    title: 'ECO Friendly Mud House project Dindigul. Interlocking Bricks & Stone',
    youtube_id: 'mN3kL8wX2pQ',
    description: 'Turnkey eco mud house project execution at Dindigul.',
    visible: true,
    sort_order: 8,
  },
  {
    id: 'vid-9',
    title: 'Interlocking Mud bricks House & Bamboo cottage Beach Resort Construction @ Kumta',
    youtube_id: 'xP9kL2wN7mQ',
    description: 'Coastal beach resort and bamboo cottages constructed using interlocking mud blocks in Kumta.',
    visible: true,
    sort_order: 9,
  },
  {
    id: 'vid-10',
    title: 'Filler Slab Installation',
    youtube_id: 'cL4mN8pQ2wX',
    description: 'Lightweight eco-friendly filler slab casting to reduce concrete and dead load while cooling ceiling.',
    visible: true,
    sort_order: 10,
  },
  {
    id: 'vid-11',
    title: 'Compressed Soil Earth Blocks CSEB / Interlocking Earth bricks ECO friendly house',
    youtube_id: 'wK3mL9pX2nQ',
    description: 'Technical overview of CSEB block compaction and dry-stack interlocking alignment.',
    visible: true,
    sort_order: 11,
  },
  {
    id: 'vid-12',
    title: 'Built with Interlocking Soil Brick – Academic Building',
    youtube_id: 'rQ7kL2mN9wX',
    description: 'Institutional academic campus block built with sustainable soil compressed brick architecture.',
    visible: true,
    sort_order: 12,
  },
  {
    id: 'vid-13',
    title: 'ECO Friendly House Construction – Interlocking Mud Brick',
    youtube_id: 'yN8kL2mP3wX',
    description: 'Complete eco-friendly home construction lifecycle from foundation to finished roof.',
    visible: true,
    sort_order: 13,
  }
];

export const PROJECT_CATEGORIES = [
  'All',
  'Residential House',
  'Villa & Bungalow',
  'Resorts & Cottages',
  'Traditional Courtyard',
  'Farmhouse',
  'Commercial Building',
  'Academic Building',
  'Raw Materials'
];

export const SERVICES_LIST = [
  {
    title: 'Budget House',
    description: 'Cost-effective, highly durable homes built with interlocking soil bricks that eliminate plastering and cement mortar expenses.',
    icon: 'Home',
    features: ['Up to 60% cement savings', 'Fast-track completion', 'Natural thermal insulation']
  },
  {
    title: 'Villa & Bungalow',
    description: 'Custom-designed sustainable villas featuring exposed earthy finishes, spacious verandas, and high ceiling cross-ventilation.',
    icon: 'Building2',
    features: ['Turnkey architectural design', 'Custom filler slabs', 'Luxury eco-finishings']
  },
  {
    title: 'Group & Community Housing',
    description: 'Eco-conscious residential colonies and row houses engineered with modular interlocking brick systems for rapid development.',
    icon: 'Users',
    features: ['Standardized structural modules', 'Low carbon footprint', 'Community rainwater integration']
  },
  {
    title: 'Traditional Courtyard House',
    description: 'Authentic heritage-inspired courtyard homes (Thotti Mane / Nadumuttam) that blend ancient Vastu-based climate wisdom with modern earth engineering.',
    icon: 'Sparkles',
    features: ['Central light & breeze wells', 'CSEB earth columns', 'Clay tile roofing']
  },
  {
    title: 'Resorts & Cottages',
    description: 'Serene nature cottages, homestays, and eco-resort cabins built using natural stone, CSEB blocks, and bamboo accents.',
    icon: 'Palmtree',
    features: ['Harmonious rustic aesthetic', 'Zero chemical emissions', 'Cool interior climate']
  },
  {
    title: 'Commercial & Academic',
    description: 'Environmentally responsible office spaces, eco-schools, training institutions, and farmhouses crafted for longevity and low energy bills.',
    icon: 'GraduationCap',
    features: ['High structural load rating', 'Reduced HVAC energy costs', 'Timeless organic appearance']
  }
];
